[deps]
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
FlexiChains = "4a37a8b9-6e57-4b92-8664-298d46e639f7"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
